### ISSUE TITLE
🐳 Dockerize LectureCut

### ISSUE THREAD

**Issue by Gamer92000** [Gamer92000/LectureCut#1]
# LectureCut needs to be dockerized.

This includes
- writing a `Dockerfile` (preferably using a `.dockerignore` instead of copying files manually),
- writing a workflow, and
- update the README.

## Dockerfile
The Dockerfile should build a self-contained container that is as usable as the native CLI.
It should be as easy as possible to get files into and out of the container.
Before implementing this we should discuss the options for sharing files from the host (as I am not really experienced with these kind of things).

## Workflow
The workflow should run on tags (`v*`) on the `main` branch. It needs to build a docker image based on the Dockerfile and upload it to `ghcr` for now.

## README
The readme needs to include all the relevant steps to start using the dockerized version and list the advantages and drawbacks of using it.

**Comment by pogzyb** [comment]
Hi - I can work on this.

**Comment by pogzyb** [comment]
> 

Awesome! Thanks for confirming.
